### ISSUE TITLE
Pidman (Templates) Python 3

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/pidman#3]
Upgrade pidman templates from python 2 to python 3. Update all deprecated methods from Django 1.8 to Django 3

**Comment by tmiles2** [comment]
Zo is gone to a conference until 10/27.

**Comment by alexBLR** [comment]
- [x] removed boostrapped_admin (deprecated)
- [x] installed django-jazzmin admin panel
- [x] removed eultheme (deprecated)
- [x] removed eultheme dependencies
- [x] adjusted 404,500, 401 html pages
- [x] removed deprecated packages from admin.py
- [x] adjusted emory templates to reflect a new admin panel
