### ISSUE TITLE
Pidman (Management Commands) Python 3

### ISSUE THREAD

**Issue by alexBLR** [emory-libraries/pidman#5]
Upgrade pidman management commands from python 2 to python 3. Update all deprecated methods from Django 1.8 to Django 3

**Comment by tmiles2** [comment]
@alexBLR Don't forget to update this ticket before our meeting.

**Comment by alexBLR** [comment]
- [x] updated allocate_pids to python3
- [x] updated migrate_lsdi_arks to python3
- [x] updated migrate_pid_urls to python3
- [x] updated migrate_rushdie_arks to python3
- [x] updates datamigrate to python3
